### ISSUE TITLE
No fixtures found.

### ISSUE THREAD

**Issue by shake** [managedit/openstack-setup#5]
when I run the script. 

I find the 
/usr/share/openstack-dashboard/dashboard/manage.py syncdb

would report the error : No fixtures found.

how to do ?

root@node3:~/openstack-setup# ./dashboard.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
libapache2-mod-wsgi is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
openstack-dashboard is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.
INFO:root:Running in debug mode without debug_toolbar.
INFO:root:Running in debug mode without debug_toolbar.
DEBUG:django.db.backends:(0.000) SHOW TABLES; args=()
Creating tables ...
Creating table django_content_type
DEBUG:django.db.backends:(0.028) CREATE TABLE `django_content_type` (
    `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` varchar(100) NOT NULL,
    `app_label` varchar(100) NOT NULL,
    `model` varchar(100) NOT NULL,
    UNIQUE (`app_label`, `model`)
)
;; args=()
Creating table django_session
DEBUG:django.db.backends:(0.022) CREATE TABLE `django_session` (
    `session_key` varchar(40) NOT NULL PRIMARY KEY,
    `session_data` longtext NOT NULL,
    `expire_date` datetime NOT NULL
)
;; args=()
Creating table mailer_message
DEBUG:django.db.backends:(0.016) CREATE TABLE `mailer_message` (
    `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `message_data` longtext NOT NULL,
    `when_added` datetime NOT NULL,
    `priority` varchar(1) NOT NULL
)
;; args=()
Creating table mailer_dontsendentry
DEBUG:django.db.backends:(0.015) CREATE TABLE `mailer_dontsendentry` (
    `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `to_address` varchar(75) NOT NULL,
    `when_added` datetime NOT NULL
)
;; args=()
Creating table mailer_messagelog
DEBUG:django.db.backends:(0.017) CREATE TABLE `mailer_messagelog` (
    `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `message_data` longtext NOT NULL,
    `when_added` datetime NOT NULL,
    `priority` varchar(1) NOT NULL,
    `when_attempted` datetime NOT NULL,
    `result` varchar(1) NOT NULL,
    `log_message` longtext NOT NULL
)
;; args=()
DEBUG:django.db.backends:(0.001) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = contenttypes  ORDER BY `django_content_type`.`name` ASC; args=('contenttypes',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = contenttype  AND `django_content_type`.`app_label` = contenttypes ); args=('contenttype', 'contenttypes')
DEBUG:django.db.backends:(0.000) INSERT INTO `django_content_type` (`name`, `app_label`, `model`) VALUES (content type, contenttypes, contenttype); args=(u'content type', 'contenttypes', 'contenttype')
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = sessions  ORDER BY `django_content_type`.`name` ASC; args=('sessions',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = session  AND `django_content_type`.`app_label` = sessions ); args=('session', 'sessions')
DEBUG:django.db.backends:(0.000) INSERT INTO `django_content_type` (`name`, `app_label`, `model`) VALUES (session, sessions, session); args=(u'session', 'sessions', 'session')
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = messages  ORDER BY `django_content_type`.`name` ASC; args=('messages',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = staticfiles  ORDER BY `django_content_type`.`name` ASC; args=('staticfiles',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = django_openstack  ORDER BY `django_content_type`.`name` ASC; args=('django_openstack',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = mailer  ORDER BY `django_content_type`.`name` ASC; args=('mailer',)
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = message  AND `django_content_type`.`app_label` = mailer ); args=('message', 'mailer')
DEBUG:django.db.backends:(0.000) INSERT INTO `django_content_type` (`name`, `app_label`, `model`) VALUES (message, mailer, message); args=(u'message', 'mailer', 'message')
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = dontsendentry  AND `django_content_type`.`app_label` = mailer ); args=('dontsendentry', 'mailer')
DEBUG:django.db.backends:(0.000) INSERT INTO `django_content_type` (`name`, `app_label`, `model`) VALUES (don't send entry, mailer, dontsendentry); args=(u"don't send entry", 'mailer', 'dontsendentry')
DEBUG:django.db.backends:(0.000) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = messagelog  AND `django_content_type`.`app_label` = mailer ); args=('messagelog', 'mailer')
DEBUG:django.db.backends:(0.000) INSERT INTO `django_content_type` (`name`, `app_label`, `model`) VALUES (message log, mailer, messagelog); args=(u'message log', 'mailer', 'messagelog')
Installing custom SQL ...
Installing indexes ...
DEBUG:django.db.backends:(0.032) CREATE INDEX `django_session_c25c2c28` ON `django_session` (`expire_date`);; args=()
No fixtures found.
root@node3:~/openstack-setup#

**Comment by cryptk** [comment]
That is not a bug, please reference the OpenStack deployment docs, specifically http://docs.openstack.org/diablo/openstack-compute/install/content/configure-dashboard.html

You will see that if everything go's as planned, the last few lines of output are:

> Installing custom SQL ...
> Installing indexes ...
> DEBUG:django.db.backends:(0.008) CREATE INDEX `django_session_c25c2c28` ON `django_session` (`expire_date`);; args=()
> No fixtures found.

**Comment by shake** [comment]
thanks fro your reply.
